### ISSUE TITLE
HTML Formatting?

### ISSUE THREAD

**Issue by AlexanderNeumann** [rwth-acis/LMS-chatbot-service#1]
If the bot is connected to Moodle it needs HTML formatting. I am unsure if this issue is more related to the bot manager service... 

here an example: 

> Ein ER-Modell für eine Hochschule könnte folgendermaßen aussehen:\n\nEntity-Typen könnten sein: <Student>, <Professor>, <Kurs>, <Fachbereich>\n\nBeziehungen könnten sein: \n\n- <Student> nimmt teil an <Kurs> - Dies wäre eine m:n-Beziehung, da ein Student an mehreren Kursen teilnehmen kann und ein Kurs von mehreren Studenten besucht wird.\n- <Professor> lehrt <Kurs> - Dies wäre eine 1:n-Beziehung, da ein Professor mehrere Kurse lehren kann, aber ein Kurs in der Regel von einem Professor gelehrt wird.\n- <Professor> gehört zu <Fachbereich> - Dies wäre eine m:1-Beziehung, da ein Professor zu genau einem Fachbereich gehört, aber ein Fachbereich mehrere Professoren haben kann.\n- <Student> studiert <Fachbereich> - Dies wäre eine m:1-Beziehung, da ein Student in genau einem Fachbereich studiert, aber ein Fachbereich mehrere Studenten haben kann.\n\nBitte beachten Sie, dass dies nur ein einfaches Beispiel ist und ein tatsächliches ER-Modell für eine Hochschule viel komplexer sein könnte, abhängig von den spezifischen Anforderungen und dem Kontext.

Result: 

![grafik](https://github.com/rwth-acis/LMS-chatbot-service/assets/10010710/e213deab-176f-41a0-8acc-f1980a57df7f)

snippets like `<Student>` are recognized as html tags? and will not appear in the chat message.

**Comment by Yinnii** [comment]
fixed within the las2peer service 
![image](https://github.com/rwth-acis/LMS-chatbot-service/assets/92319388/befb4632-4e91-4a85-b89d-a61513035eaf)

The brackets are replaced.
